version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: articles_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://root:root@mysql-container:3306/articles_db
      REDIS_URL: redis://redis-container:6379
    ports:
      - "3001:3001"
      - "5555:5555"
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
    restart: always
    command: >
      sh -c "npm run prisma:migrate && npm start"

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
